on:
  pull_request:
    branches:
      - master
    types: [closed]

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        if: contains(github.event.pull_request.title, 'Release')
        uses: actions/checkout@master
      - name: Create tag name
        id: tag_name
        if: contains(github.event.pull_request.title, 'Release')
        run: |
          tagname="${pull_request_title//Release }"
          echo $tagname
          echo "::set-output name=tagname::$tagname"
        env:
          pull_request_title: ${{ github.event.pull_request.title }}
      - name: Create Release
        if: contains(github.event.pull_request.title, 'Release')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.tag_name.outputs.tagname }}
          release_name: ${{ github.event.pull_request.title }}
          body: | 
            ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
